#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iw
Version  : 5.4
Release  : 11
URL      : https://mirrors.kernel.org/pub/software/network/iw/iw-5.4.tar.xz
Source0  : https://mirrors.kernel.org/pub/software/network/iw/iw-5.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: iw-bin = %{version}-%{release}
Requires: iw-license = %{version}-%{release}
Requires: iw-man = %{version}-%{release}
BuildRequires : libnl-dev

%description
This is 'iw', a tool to use nl80211.
To build iw, just enter 'make'. If that fails, set the
PKG_CONFIG_PATH environment variable to allow the Makefile
to find libnl.

%package bin
Summary: bin components for the iw package.
Group: Binaries
Requires: iw-license = %{version}-%{release}

%description bin
bin components for the iw package.


%package license
Summary: license components for the iw package.
Group: Default

%description license
license components for the iw package.


%package man
Summary: man components for the iw package.
Group: Default

%description man
man components for the iw package.


%prep
%setup -q -n iw-5.4
cd %{_builddir}/iw-5.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1594670781
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1594670781
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iw
cp %{_builddir}/iw-5.4/COPYING %{buildroot}/usr/share/package-licenses/iw/733f780e306fe2b5c9aa92b45372ffb07978b35e
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iw

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iw/733f780e306fe2b5c9aa92b45372ffb07978b35e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/iw.8.gz
