#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iw
Version  : 5.0.1
Release  : 8
URL      : https://www.kernel.org/pub/software/network/iw/iw-5.0.1.tar.xz
Source0  : https://www.kernel.org/pub/software/network/iw/iw-5.0.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: iw-bin = %{version}-%{release}
Requires: iw-license = %{version}-%{release}
Requires: iw-man = %{version}-%{release}
BuildRequires : libnl-dev

%description
This is 'iw', a tool to use nl80211.
To build iw, just enter 'make'. If that fails, set the
PKG_CONFIG_PATH environment variable to allow the Makefile
to find libnl.

%package bin
Summary: bin components for the iw package.
Group: Binaries
Requires: iw-license = %{version}-%{release}
Requires: iw-man = %{version}-%{release}

%description bin
bin components for the iw package.


%package license
Summary: license components for the iw package.
Group: Default

%description license
license components for the iw package.


%package man
Summary: man components for the iw package.
Group: Default

%description man
man components for the iw package.


%prep
%setup -q -n iw-5.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549299150
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1549299150
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iw
cp COPYING %{buildroot}/usr/share/package-licenses/iw/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iw

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iw/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/iw.8.gz
